author_id = "lux"
app_id = "gates"
author_name = "Lux"
app_name = "Through the Gate"

[files]
_splash = { path = "splash.png" }
font = { path = "font.fff", url = "https://fonts.fireflyzero.com/fonts/ascii/ibm437r_8x8.fff" }
